#!/bin/bash -e
# regenerate wordpress secrets and mysql password

. /etc/default/inithooks

updateconf() {
    CONF=/var/www/opencart/config.php
    ADMINCONF=/var/www/opencart/admin/config.php
    sed -i "s/\(.*\)$1\(.*\)');/define('$1', '$2');/;" $CONF
    sed -i "s/\(.*\)$1\(.*\)');/define('$1', '$2');/;" $ADMINCONF
}


PASSWORD=$(mcookie)
updateconf 'DB_PASSWORD' $PASSWORD
$INITHOOKS_PATH/bin/mysqlconf.py --user=opencart --pass="$PASSWORD"
